### ISSUE TITLE
Feedback for Lab Report 2

### ISSUE THREAD

**Issue by emjinn** [Jiaying6429/Lab-Reports#2]
Here is your feedback for Lab Report 2:

- [x] Correct screenshot of code diff page
- [x] Correct failure inducing test file - 1
- [x] Correct failure inducing test file - 2
- [x] Correct failure inducing test file - 3
- [x] Screenshot of symptom output that caused the failure for test file - 1
- [x] Screenshot of symptom output that caused the failure for test file - 2
- [x] Screenshot of symptom output that caused the failure for test file - 3
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 1
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 2
- [x] Correct description for the relationship between the bug, the symptom, and the failure-inducing input for file - 3
- [x] Correct markdown formatting
- [x] Lab report is on its own page, not the index page
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Make sure to link the failure-inducing test files that you had used on your Lab Report! 

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by emjinn** [comment]
The code diff screenshot should reflect the changes that you made to MarkdownParse.java, not the test-file#.md files. For future labs, please submit a regrade request, rather than making a late submission

**Comment by Jiaying6429** [comment]
> 

Hi but I didn't lose any points when I got my first lab report 2 grade and I didn't change my screenshot at all. It seems a bit unfair for me to lose a point without knowing I should change that. May I have that point back or may I have another chance to correct that?

**Comment by emjinn** [comment]
Granted the point back! Apologies for the miscommunication initially. For future labs, however, please read the lab instructions carefully to ensure that you have the correct details on your report! Once again, I apologize for the miscommunication :')

**Comment by Jiaying6429** [comment]
Thank you so much! I will definitely read the write-up more carefully next time and double check details!
